v 1.7

diff --git a/assignment_16/Dockerfile b/assignment_16/Dockerfile
--- a/assignment_16/Dockerfile
+++ b/assignment_16/Dockerfile
@@ -7,7 +7,7 @@ COPY package*.json ./
 RUN npm install
 
 COPY . .
-RUN npm run build
+RUN npm install || (echo "==== NPM INSTALL FAILED ====" && cat /root/.npm/_logs/* || true)
 
 FROM nginx:alpine
 COPY --from=build /app/build /usr/share/nginx/html
